version: '3'

services:
  nodejs:
    image: node:14
    container_name: nodejs_service
    volumes:
      - ./nodejs-service:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx_service
    volumes:
      - ./nginx-service/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-service/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
